name: Build Docker Image

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
    outputs:
      tag:
        description: "Docker image tag"
        value: ${{ jobs.build.outputs.tag }}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    outputs:
      tag: ${{ steps.export-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Definir TAG
        id: export-tag
        run: echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ inputs.IMAGE_NAME }}:${{ steps.export-tag.outputs.tag }} .
          docker tag ${{ inputs.IMAGE_NAME }}:${{ steps.export-tag.outputs.tag }} ${{ inputs.IMAGE_NAME }}:latest

      - name: Push da imagem Docker
        run: |
          docker push ${{ inputs.IMAGE_NAME }}:${{ steps.export-tag.outputs.tag }}
          docker push ${{ inputs.IMAGE_NAME }}:latest
